"""add_bilingual_clause_fields

Revision ID: 0e180067cb32
Revises: fd06d29886f0
Create Date: 2025-12-03 12:43:05.591071
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e180067cb32'
down_revision = 'fd06d29886f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clauses', sa.Column('english_text', sa.Text(), nullable=True))
    op.add_column('clauses', sa.Column('arabic_text', sa.Text(), nullable=True))
    op.add_column('clauses', sa.Column('is_bilingual', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clauses', 'is_bilingual')
    op.drop_column('clauses', 'arabic_text')
    op.drop_column('clauses', 'english_text')
    # ### end Alembic commands ###
