"""make_explanation_nullable

Revision ID: fd06d29886f0
Revises: 4bb127237fc6
Create Date: 2025-12-03 08:12:32.957201
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd06d29886f0'
down_revision = '4bb127237fc6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conflicts', 'explanation',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conflicts', 'explanation',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
